# Also usable in cmake -P mode for offline validation of configuration guards.
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Android")
    message(FATAL_ERROR "This diagnostic requires an Android NDK toolchain; macOS objects are not Android code.")
endif()
if(NOT ANDROID_ABI STREQUAL "arm64-v8a")
    message(FATAL_ERROR "The initial Android diagnostic only targets arm64-v8a; a 32-bit OS is outside this plan.")
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "The diagnostic requires 64-bit host pointers.")
endif()
if(NOT CMAKE_SYSTEM_VERSION MATCHES "^[0-9]+$")
    message(FATAL_ERROR "Set a numeric Android API level through the NDK toolchain.")
endif()
if(CMAKE_SYSTEM_VERSION LESS 30)
    message(FATAL_ERROR "The initial probe requires Android API 30 or newer for memfd_create.")
endif()
message(STATUS "Android ARM64 configuration gate passed; no runtime/device support is implied.")
